apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels: { app: kafka }
  template:
    metadata: { labels: { app: kafka } }
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.7
          ports: [{ containerPort: 9092 }]
          env:
            - { name: KAFKA_CFG_NODE_ID, value: "1" }
            - { name: KAFKA_CFG_PROCESS_ROLES, value: broker,controller }
            - { name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS, value: 1@kafka:9093 }
            - { name: KAFKA_CFG_LISTENERS, value: PLAINTEXT://:9092,CONTROLLER://:9093 }
            - { name: KAFKA_CFG_ADVERTISED_LISTENERS, value: PLAINTEXT://kafka:9092 }
            - { name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES, value: CONTROLLER }
            - { name: ALLOW_PLAINTEXT_LISTENER, value: "yes" }
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ecommerce
spec:
  selector: { app: kafka }
  ports: [{ port: 9092, targetPort: 9092 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels: { app: mongo }
  template:
    metadata: { labels: { app: mongo } }
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports: [{ containerPort: 27017 }]
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: ecommerce
spec:
  selector: { app: mongo }
  ports: [{ port: 27017, targetPort: 27017 }]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: ecommerce
data:
   init.sql: |
    CREATE DATABASE payments;
    CREATE DATABASE notifications;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: ecommerce
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports: [{ containerPort: 5432 }]
          env:
            - { name: POSTGRES_DB, value: orders }
            - { name: POSTGRES_USER, value: ecommerce }
            - { name: POSTGRES_PASSWORD, value: ecommerce }
          volumeMounts:
            - { name: postgres-data, mountPath: /var/lib/postgresql/data }
            - { name: postgres-init, mountPath: /docker-entrypoint-initdb.d/00-init.sql, subPath: init.sql }
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata: { name: postgres-data }
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests: { storage: 5Gi }
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ecommerce
spec:
  selector: { app: postgres }
  ports: [{ port: 5432, targetPort: 5432 }]